// Automatically generated by flapigen
package org.iota.client;


public final class AddressDto {
    @Override
    public String toString() {
        return this.to_string();
    }


    private AddressDto() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public final short kind() {
        short ret = do_kind(mNativeObj);

        return ret;
    }
    private static native short do_kind(long self);

    public final String address() {
        String ret = do_address(mNativeObj);

        return ret;
    }
    private static native String do_address(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AddressDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}