// Automatically generated by flapigen
package org.iota.client;


public final class Essence {
    @Override
    public String toString() {
        return this.to_string();
    }


    private Essence() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public final java.util.Optional<RegularEssence> getAsRegular() {
        long ret = do_getAsRegular(mNativeObj);
        java.util.Optional<RegularEssence> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new RegularEssence(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_getAsRegular(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Essence(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}