// Automatically generated by flapigen
package org.iota.client;


public final class GossipDto {

    private GossipDto() {}

    public final HeartbeatDto heartbeat() {
        long ret = do_heartbeat(mNativeObj);
        HeartbeatDto convRet = new HeartbeatDto(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_heartbeat(long self);

    public final MetricsDto metrics() {
        long ret = do_metrics(mNativeObj);
        MetricsDto convRet = new MetricsDto(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_metrics(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ GossipDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}