// Automatically generated by flapigen
package org.iota.client;


public final class HeartbeatDto {

    private HeartbeatDto() {}

    public final long solidMilestoneIndex() {
        long ret = do_solidMilestoneIndex(mNativeObj);

        return ret;
    }
    private static native long do_solidMilestoneIndex(long self);

    public final long prunedMilestoneIndex() {
        long ret = do_prunedMilestoneIndex(mNativeObj);

        return ret;
    }
    private static native long do_prunedMilestoneIndex(long self);

    public final long latestMilestoneIndex() {
        long ret = do_latestMilestoneIndex(mNativeObj);

        return ret;
    }
    private static native long do_latestMilestoneIndex(long self);

    public final short connectedNeighbors() {
        short ret = do_connectedNeighbors(mNativeObj);

        return ret;
    }
    private static native short do_connectedNeighbors(long self);

    public final short syncedNeighbors() {
        short ret = do_syncedNeighbors(mNativeObj);

        return ret;
    }
    private static native short do_syncedNeighbors(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ HeartbeatDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}