// Automatically generated by flapigen
package org.iota.client;


public final class ReceiptDto {
    @Override
    public String toString() {
        return this.to_string();
    }


    private ReceiptDto() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public final long milestoneIndex() {
        long ret = do_milestoneIndex(mNativeObj);

        return ret;
    }
    private static native long do_milestoneIndex(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ReceiptDto(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}