// Automatically generated by flapigen
package org.iota.client;


public final class TreasuryInput {
    @Override
    public String toString() {
        return this.to_string();
    }


    public TreasuryInput(MilestoneId milestone) {
        long a0 = milestone.mNativeObj;
        milestone.mNativeObj = 0;

        mNativeObj = init(a0);
        JNIReachabilityFence.reachabilityFence1(milestone);
    }
    private static native long init(long milestone);

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);
    /**
     * Returns the milestones id of a `TreasuryInput`.
     */
    public final MilestoneId milestoneId() {
        long ret = do_milestoneId(mNativeObj);
        MilestoneId convRet = new MilestoneId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_milestoneId(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TreasuryInput(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}