// Automatically generated by flapigen
package org.iota.client;


public final class UnlockBlock {
    @Override
    public String toString() {
        return this.to_string();
    }


    private UnlockBlock() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public final UnlockBlockKind kind() {
        int ret = do_kind(mNativeObj);
        UnlockBlockKind convRet = UnlockBlockKind.fromInt(ret);

        return convRet;
    }
    private static native int do_kind(long self);

    public final java.util.Optional<ReferenceUnlock> getAsReference() {
        long ret = do_getAsReference(mNativeObj);
        java.util.Optional<ReferenceUnlock> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new ReferenceUnlock(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_getAsReference(long self);

    public final java.util.Optional<SignatureUnlock> getAsSignature() {
        long ret = do_getAsSignature(mNativeObj);
        java.util.Optional<SignatureUnlock> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new SignatureUnlock(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_getAsSignature(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ UnlockBlock(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}