// Automatically generated by flapigen
package org.iota.client;


public final class UtxoInput {
    @Override
    public String toString() {
        return this.to_string();
    }


    private UtxoInput() {}

    private final String to_string() {
        String ret = do_to_string(mNativeObj);

        return ret;
    }
    private static native String do_to_string(long self);

    public static UtxoInput from(TransactionId id, int index) {
        long a0 = id.mNativeObj;
        id.mNativeObj = 0;

        long ret = do_from(a0, index);
        UtxoInput convRet = new UtxoInput(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(id);

        return convRet;
    }
    private static native long do_from(long id, int index);

    public final byte [] transactionId() {
        byte [] ret = do_transactionId(mNativeObj);

        return ret;
    }
    private static native byte [] do_transactionId(long self);

    public final int index() {
        int ret = do_index(mNativeObj);

        return ret;
    }
    private static native int do_index(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ UtxoInput(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}