{
 "title": "Blockchain Balance V2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gas Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_price{service=\"ethereum-service\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "gas_price{service=\"ethereum-classic-service\"}",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_limit{service=\"ethereum-service\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "gas_limit{service=\"ethereum-classic-service\"}",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "Used Delta",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "used_delta{service=\"ethereum-service\"} * 100",
     "legendFormat": "ETH"
    },
    {
     "expr": "used_delta{service=\"ethereum-classic-service\"} * 100",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "Time Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "time_used{service=\"ethereum-service\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "time_used{service=\"ethereum-classic-service\"}",
     "legendFormat": "ETC"
    },
    {
     "expr": "time_used{service=\"iota-service\"}",
     "legendFormat": "IOTA"
    }
   ]
  },
  {
   "title": "ETH and ETC",
   "type": "gauge",
   "description": "Shows how much Ether we got.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "current_balance{service=\"ethereum-service\"}/1000000000000000000",
     "legendFormat": "ETH"
    },
    {
     "expr": "current_balance{service=\"ethereum-classic-service\"}/1000000000000000000",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Ether" }
   ],
   "targets": [
    {
     "expr": "current_balance{service=\"ethereum-service\"}/1000000000000000000",
     "legendFormat": "ETH"
    }
   ]
  },
  {
   "title": "Ethereum Classic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Gwei" }
   ],
   "targets": [
    {
     "expr": "current_balance{service=\"ethereum-classic-service\"}/1000000000000000000",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "Gas used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_used{service=\"ethereum-service\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "gas_used{service=\"ethereum-classic-service\"}",
     "legendFormat": "ETC"
    }
   ]
  },
  {
   "title": "IOTA-TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "TX" }
   ],
   "targets": [
    {
     "expr": "transaction_success{service=\"iota-service\"}",
     "legendFormat": "IOTA"
    }
   ]
  },
  {
   "title": "TX-Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "transaction_success{service=\"ethereum-service\"}",
     "legendFormat": "ETH-TX"
    },
    {
     "expr": "transaction_success{service=\"ethereum-service-ethereum-service\"}",
     "legendFormat": "ETC-TX"
    }
   ]
  }
 ]
}